CREATE DATABASE  IF NOT EXISTS `bdm`;

--

DROP TABLE IF EXISTS `comentarios`;
CREATE TABLE `comentarios` (
  `ID_COMENTARIO` int NOT NULL,
  `ID_USUARIO` int NOT NULL,
  `COMENTARIO` varchar(100) NOT NULL,
  `ID_PUBLIACION` int NOT NULL,
  PRIMARY KEY (`ID_COMENTARIO`),
  KEY `ID_PUBLICACION_COMENTARIO_idx` (`ID_PUBLIACION`),
  KEY `ID_PUBLICACION_USUARIO_idx` (`ID_USUARIO`),
  CONSTRAINT `ID_PUBLICACION_COMENTARIO` FOREIGN KEY (`ID_PUBLIACION`) REFERENCES `publicaciones` (`ID_PUBLICACION`),
  CONSTRAINT `ID_PUBLICACION_USUARIO` FOREIGN KEY (`ID_USUARIO`) REFERENCES `usuarios` (`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='				';

--
-- Table structure for table `multimedia`
--

DROP TABLE IF EXISTS `multimedia`;
CREATE TABLE `multimedia` (
  `ID_MULTIMEDIA` int NOT NULL,
  `RUTA_VIDEO` varchar(255) DEFAULT NULL,
  `FOTO` mediumblob,
  `TIPO_IMG` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`ID_MULTIMEDIA`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `publicaciones`
--

DROP TABLE IF EXISTS `publicaciones`;
CREATE TABLE `publicaciones` (
  `ID_PUBLICACION` int NOT NULL AUTO_INCREMENT,
  `DESCRIPCION` varchar(200) NOT NULL,
  `ID_MULTIMEDIA` int NOT NULL,
  `ID_USUARIO` int NOT NULL,
  `CATEGORIA` varchar(50) NOT NULL,
  `ESTATUS` tinyint NOT NULL,
  `FECHA_CREACION` datetime NOT NULL,
  `CONTADOR_LIKES` int NOT NULL,
  PRIMARY KEY (`ID_PUBLICACION`),
  KEY `ID_MULTIMEDIA_PUBLICACION_idx` (`ID_MULTIMEDIA`),
  KEY `ID_USUARIO_PUBLICACION_idx` (`ID_USUARIO`),
  CONSTRAINT `ID_MULTIMEDIA_PUBLICACION` FOREIGN KEY (`ID_MULTIMEDIA`) REFERENCES `multimedia` (`ID_MULTIMEDIA`),
  CONSTRAINT `ID_USUARIO_PUBLICACION` FOREIGN KEY (`ID_USUARIO`) REFERENCES `usuarios` (`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `reacciones`
--

DROP TABLE IF EXISTS `reacciones`;
CREATE TABLE `reacciones` (
  `ID_REACCION` int NOT NULL,
  `ID_USUARIO` int NOT NULL,
  `ID_PUBLICACION` int NOT NULL,
  PRIMARY KEY (`ID_REACCION`),
  KEY `ID_REACCION_USUARIO_idx` (`ID_USUARIO`),
  KEY `ID_REACCION_PUBLICACION_idx` (`ID_PUBLICACION`),
  CONSTRAINT `ID_REACCION_PUBLICACION` FOREIGN KEY (`ID_PUBLICACION`) REFERENCES `publicaciones` (`ID_PUBLICACION`),
  CONSTRAINT `ID_REACCION_USUARIO` FOREIGN KEY (`ID_USUARIO`) REFERENCES `usuarios` (`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `seguidores`
--

DROP TABLE IF EXISTS `seguidores`;
CREATE TABLE `seguidores` (
  `ID_SEGUIDOR` int NOT NULL,
  `ID_USUARIO_SEGUIDO` int NOT NULL,
  `ID_USUARIO_SEGUIDOR` int NOT NULL,
  PRIMARY KEY (`ID_SEGUIDOR`),
  KEY `ID_USUARIOS_SEGUDIOR_idx` (`ID_USUARIO_SEGUIDOR`),
  KEY `ID_USUARIO_SEGUDIO_idx` (`ID_USUARIO_SEGUIDO`),
  CONSTRAINT `ID_USUARIO_SEGUDIO` FOREIGN KEY (`ID_USUARIO_SEGUIDO`) REFERENCES `usuarios` (`ID_USUARIO`),
  CONSTRAINT `ID_USUARIOS_SEGUDIOR` FOREIGN KEY (`ID_USUARIO_SEGUIDOR`) REFERENCES `usuarios` (`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `tablero_detalle`
--

DROP TABLE IF EXISTS `tablero_detalle`;
CREATE TABLE `tablero_detalle` (
  `ID_DETALLE` int NOT NULL AUTO_INCREMENT,
  `ID_TABLERO` int NOT NULL,
  `ID_PUBLICACION` int NOT NULL,
  PRIMARY KEY (`ID_DETALLE`),
  KEY `ID_TABLERO_PUBLICACION_idx` (`ID_PUBLICACION`),
  KEY `ID_TABLERO_TABLERO_idx` (`ID_TABLERO`),
  CONSTRAINT `ID_TABLERO_PUBLICACION` FOREIGN KEY (`ID_PUBLICACION`) REFERENCES `publicaciones` (`ID_PUBLICACION`),
  CONSTRAINT `ID_TABLERO_TABLERO` FOREIGN KEY (`ID_TABLERO`) REFERENCES `tableros` (`ID_TABLERO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `tableros`
--

DROP TABLE IF EXISTS `tableros`;
CREATE TABLE `tableros` (
  `ID_TABLERO` int NOT NULL AUTO_INCREMENT,
  `ID_USUARIO` int NOT NULL,
  `TITULO` varchar(80) NOT NULL,
  PRIMARY KEY (`ID_TABLERO`),
  KEY `ID_USUARIO_TABLERO_idx` (`ID_USUARIO`),
  CONSTRAINT `ID_USUARIO_TABLERO` FOREIGN KEY (`ID_USUARIO`) REFERENCES `usuarios` (`ID_USUARIO`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Table structure for table `usuarios`
--

DROP TABLE IF EXISTS `usuarios`;
CREATE TABLE `usuarios` (
  `ID_USUARIO` int NOT NULL AUTO_INCREMENT,
  `NOMBRE` varchar(50) NOT NULL,
  `APELLIDO_PATERNO` varchar(50) NOT NULL,
  `APELLIDO_MATERNO` varchar(50) NOT NULL,
  `CORREO` varchar(80) NOT NULL,
  `FECHA_NACIMINENTO` date NOT NULL,
  `SEXO` tinyint NOT NULL,
  `USERNAME` varchar(50) NOT NULL,
  `PASSWORD` varchar(60) NOT NULL,
  `FOTO_PERFIL` longblob NOT NULL,
  `ESTATUS` tinyint NOT NULL,
  `PRIVACIDAD` tinyint NOT NULL,
  `FECHA_REGISTRO` datetime NOT NULL,
  `TIPO_IMG` varchar(50) NOT NULL,
  `SEGUIDORES` int NOT NULL DEFAULT '0',
  `SEGUIDOS` int NOT NULL DEFAULT '0',
  `PUBLICACIONES` int NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID_USUARIO`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- Dump completed on 2025-04-10 19:29:50
